Adds a config option to show only changes since a particular date
webdeveric/recently-edited-content-widget pull request #1
Opened 2017-07-05 22:45 UTC by Photosynthesis

![recent-content-date-display](https://user-images.githubusercontent.com/4992900/27887996-86699132-6198-11e7-8627-85b40efde60c.png)
![recent-content-date-config-1](https://user-images.githubusercontent.com/4992900/27887999-8a17699e-6198-11e7-868a-b821e624414c.png)
![recent-content-date-config-2](https://user-images.githubusercontent.com/4992900/27888000-8c8dd816-6198-11e7-8493-62002eef5ada.png)

2017-07-06 02:58 UTC, webdeveric requested changes

2017-07-06 02:58 UTC, webdeveric commented on recently-edited-content-widget.php
> +            $args['posts_per_page'] = -1;
Please remove.

You're ignoring the `num_items` option without notifying the user.

2017-07-06 03:00 UTC, webdeveric commented
Thanks for the PR. I've been meaning to update my plugins and this'll force me to spend a little time on them.

2017-07-06 04:19 UTC, Photosynthesis commented on recently-edited-content-widget.php
> +            $args['posts_per_page'] = -1;
Trouble is, with posts_per_page set there's no way for the user to tell if they are seeing all the items in the date range or not (or to view any items beyond the num_pages limit). 

What do you think about adding pagination on the display side? 

I'm happy to remove that line, but for the use case I'm after (reviewing changes before deploying from a staging site to production) it's important that all changes within the date range can be viewed, so I would need to find a different way to make this work.

2017-07-10 04:48 UTC, webdeveric commented on recently-edited-content-widget.php
> +            $args['posts_per_page'] = -1;
Pagination would probably be a useful feature.

Right now, `num_items` has a `maxvalue` of `100`. Is that not enough? That limit can easily be changed.

2025-11-13 15:53 UTC, closed without merging